export const types = {
    CHANGE_TITLE: "CHANGE_TITLE",
    WITH_PARAMS: "WITH_PARAMS",
    ADD_TASK: "ADD_TASK",
    TOGGLE_TASK: "TOGGLE_TASK",
    DELETE_TODO: 'DELETE_TODO',
    SET_FILTER: 'SET_FILTER',
    EDIT_TODO: 'EDIT_TODO',
    SEARCH_USER_REQUEST: "SEARCH_USER_REQUEST",
    SEARCH_USER_SUCCESS: "SEARCH_USER_SUCCESS",
    SEARCH_USER_FAILURE: "SEARCH_USER_FAILURE",
    
}