export const types = {
    FETCH_CHARACTER_REQUEST: "FETCH_CHARACTER_REQUEST",
    FETCH_CHARACTER_SUCCESS: "FETCH_CHARACTER_SUCCESS",
    FETCH_CHARACTER_FAILURE: "FETCH_CHARACTER_FAILURE",
    FETCH_CAT_SUCCESS: "FETCH_CAT_SUCCESS",
    FETCH_JOKE_SUCCESS: "FETCH_JOKE_SUCCESS",
    FETCH_FACT_SUCCESS: "FETCH_FACT_SUCCESS",
    FETCH_DOG_SUCCESS: "FETCH_DOG_SUCCESS",
    FETCH_RANDOM_USER_SUCCESS: "FETCH_RANDOM_USER_SUCCESS",
    FETCH_QUOTE_SUCCESS: "FETCH_QUOTE_SUCCESS",
    FETCH_EXTINCT_ANIMAL_SUCCESS: "FETCH_EXTINCT_ANIMAL_SUCCESS",
}